### ISSUE TITLE
Error: onnxruntime-gpu version

### ISSUE THREAD

**Issue by hchen98** [Kazuhito00/Image-Processing-Node-Editor#12]
When I try to install the package dependencies on Linux (Ubuntu 22.04), I got an error:

![image](https://user-images.githubusercontent.com/12217705/181860579-42364b5f-0bca-41ac-bebf-bf83564c06e3.png)

One simple way to resolve it would be: `pip install onnxruntime-gpu` and it will install version 1.12.0, which seems to resolve the issue.

**Comment by Kazuhito00** [comment]
Thank you for your information.
I plan to modify requirements.txt and Dockerfile.

**Comment by hchen98** [comment]
Awesome, I will close this issue since it's not a big deal and an easy fix.
