### ISSUE TITLE
Dear PyGui showcase

### ISSUE THREAD

**Issue by bandit-masked** [Kazuhito00/Image-Processing-Node-Editor#13]
Hi,

I'm with the Dear PyGui team and your image processing node editor looks absolutely amazing. I'd love to add it to the [Dear PyGui showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase). For that, I'd need a GIF and a few lines of text that describe what the app is and does. 

Unfortunately, the GIFs on your readme are either too wide or too simple to fit the showcase format. Would you be willing to create a short GIF (similar to the ones in the showcase) that shows what the app can do, e.g. connecting nodes and then showing video? If so, I'd prefer a shorter, high quality GIF rather than a longer, lower quality GIF. 

Thank you!

**Comment by Kazuhito00** [comment]
Hi @bandit-masked.

Thank you for contacting me.
How about a Gif like the one below?

![Image-Processing-Node-Editor-Demo](https://user-images.githubusercontent.com/37477845/186549591-01b5f56f-aef8-4faf-9b3e-5e3f49facb40.gif)

**Comment by bandit-masked** [comment]
Hi @Kazuhito00,

I love it! I particularly like that the the video data is input for object detection, but it is also generating a real-time plot, which is a great feature of DPG.

The description on your readme says "An application that performs image processing with the node editor.
It is used for processing verification and comparison.".

Do you have anything to add to that?

For example, this is the description I put together for WeDX.

"[WeDX](https://github.com/motojinc25/WeDX) is an open-source utility built with Python and Dear PyGui. The app provides a platform for building intelligent video applications with the capability to capture, record, and analyze videos. After that, you can publish the video and insights from video to your local computer or the cloud. You can define a flow with no-code while checking in real-time so that you can combine the three types of nodes (source, processor, and sink) in the node editor, infer the video source with the AI model, and provide the result to the service or application. The source code is available in the project's [GitHub repository](https://github.com/motojinc25/WeDX)." 

Thank you for the quick response!

**Comment by bandit-masked** [comment]
Ok, so I have already added your app to the [DPG showcase](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase) with a little bit of text. It could use some more explanation, so if you can provide that, that would be great!

**Comment by Kazuhito00** [comment]
@bandit-masked 
I saw the DPG showcase.
Thank you very much for writing a detailed explanation.

**Comment by bandit-masked** [comment]
You are most welcome!

Have you posted your app on Reddit before?

I think it would do great on r/python, /madewithpython and possibly some other subreddits as well. I'd be willing to post it there as it would make a great showcase for Dear PyGui in addition to drawing more attention to your app obviously.

**Comment by DataExplorerUser** [comment]
Suggestion from the Dear PyGui Discord is to use Numba or Taichi to speed up calculations.

**Comment by Kazuhito00** [comment]
Hi, @bandit-masked.

Sorry for the late reply.

> Have you posted your app on Reddit before?

I'm not familiar with Reddit and have never posted.

**Comment by DataExplorerUser** [comment]
Yes, I have posted about several apps made with Dear PyGui, for example my own app. I think it was viewed by or shown to about 80,000 Reddit users. 

https://www.reddit.com/r/Python/comments/sp7ddv/my_first_project_raccoon_music_player_cute/ 

It's a good way to share your app with quite a few people. Depending on what you want, you can also ask for feedback or other developers to join your project and see how people respond.

Here is an overview of projects I have posted about.
https://www.reddit.com/user/reddittestpilot/submitted/

You will see that the response you get can vary greatly depending on the sub-reddit, e.g. the group you are posting in, as well as the time and day of the week. You can post in multiple sub-reddits if you want.

Let me know if you are interested and what you'd like to get out of it.
