### ISSUE TITLE
Is the framework still updated

### ISSUE THREAD

**Issue by monkeycc** [Kazuhito00/Image-Processing-Node-Editor#19]
A very excellent framework
But it seems that there is no update function

DearPyGui   Version >= v1.11.0
Python   Version >= v3.11

Are you updating to support the latest models

**Comment by Kazuhito00** [comment]
It is currently not actively updated.
Contributions are welcome.
https://github.com/Kazuhito00/Image-Processing-Node-Editor/pull/21 now supports the latest version of DearPyGUI.
